### ISSUE TITLE
Allow FeatureFlagsOptions to set registration-type of features

### ISSUE THREAD

**Issue by billbogaiv** [ritterim/RimDev.FeatureFlags#29]
Currently, all features are registered as [`Transient`](https://github.com/ritterim/RimDev.FeatureFlags/blob/263bc9a33bc1906fe9cb4af0f3808f78b2c6d042/src/RimDev.AspNetCore.FeatureFlags/IServiceCollectionExtensions.cs#L15). Instead of having to query the `IFeatureProvider` every time a feature is requested, something like `Scoped` would short-circuit this path (since the likelihood of the feature changing state during a request is low and could result in weird edge-cases).

An example use-case is a `TagHelper`. Injecting a feature into a helper and then using the helper in many places results in a lot of `IFeatureProvider` lookups.

**Comment by kendaleiv** [comment]
Any reason to not make v2 `Scoped` by default?

**Comment by tgharold** [comment]
These are now all registered as scoped, with no plans to offer transient again in v3.
